[book]
authors = ["John McNamara"]
language = "en"
multilingual = false
src = "src"
title = "Working with the rust_xlsxwriter library"

[output.html]
default-theme = "rust"

[output.html.playground]
runnable = false
